**THEORITICAL QUESTIONS**

**Q1. EXPLAIN THE PURPOSE AND ADVANTAGES OF NUMPY IN SCIENTIFIC COMPUTING AND DATA ANALYSIS. HOW DOES IT ENHANCE PYTHON'S CAPABILITIES FOR NUMERICAL OPERATIONS?**

ANS: The primary purposes of NumPy include:

**1. Efficient Data Storage and Manipulation:** NumPy arrays allow for the efficient storage of large amounts of numerical data, which can be processed in bulk.

**2. Fast Mathematical Operations:** NumPy includes a wide range of mathematical operations optimized for performance, making it well-suited for computational-heavy tasks.

**3. Foundation for Other Libraries:** NumPy serves as a foundation for many other libraries in Python’s scientific ecosystem (like Numpy,Pandas), which rely on its fast, efficient data handling capabilities.

**Advantages of NumPy in Scientific Computing and Data Analysis:**

**1. Powerful Array and Matrix Capabilities:**

**ndarray:** NumPy's core data structure, ndarray, can represent vectors, matrices, and even higher-dimensional arrays. This enables more complex data manipulation and supports scientific tasks that require multidimensional datasets.

**Broadcasting:** NumPy’s broadcasting feature allows you to perform operations on arrays of different shapes and sizes, which is especially useful for scientific computing where you might need to work with arrays that aren't always the same shape.

**2. Comprehensive Mathematical Functions:**

NumPy provides a vast array of mathematical functions for linear algebra, statistics, Fourier transforms, and more. These functions are essential for data analysis and scientific computations, as they eliminate the need for complex, custom implementations.

Functions like dot() for matrix multiplication, mean() for averaging, and std() for standard deviation make data analysis tasks straightforward and efficient.

**3. Interfacing with Other Languages:**

**C and Fortran Interfacing:** NumPy can interface with C and Fortran libraries, which is advantageous for high-performance scientific computing. You can use NumPy with libraries written in these languages, allowing the combination of Python’s ease of use with the speed of compiled languages.

**4. Foundation for Machine Learning and Data Science:**

Since machine learning algorithms involve heavy mathematical computation on large datasets, NumPy’s capabilities make it essential in this field. Libraries like scikit-learn, TensorFlow, and PyTorch are built on top of NumPy arrays or compatible with them, enabling easy integration of machine learning into data analysis workflows.

**NumPy enhances Python's capabilities for Numerical Operations by:**

1-Replacing Python Lists with Fast ndarrays:
Native Python lists are flexible but not ideal for numerical operations, especially in scientific contexts. NumPy arrays (ndarray) replace lists for numerical data, improving both memory efficiency and speed.

2-Optimized Mathematical Operations:
With NumPy, mathematical operations can be performed in a highly optimized manner due to its C-based implementation, making computations significantly faster than with standard Python.

3-Enabling Complex Calculations:
From linear algebra to matrix decompositions and Fourier transforms, NumPy equips Python with the computational tools needed for advanced scientific applications.



**Q2. COMPARE AND CONTRAST np.mean() and np.average() FUNCTIONS IN NUMPY.WHEN WOULD YOU USE ONE OVER OTHER?**

**ANS:** In NumPy, both np.mean() and np.average() are used to calculate the average of an array or list of numbers, but they have some differences in functionality and usage.

**np.mean():**

Calculates the arithmetic mean (or simple average) of the elements in an array. This function operates over the specified axis and doesn’t take weights into account.

**np.average():**

Also calculates the arithmetic mean, but with the added option of computing a weighted average if weights are provided. When weights are not specified, it behaves similarly to np.mean().

**When to Use Each Function**

**Use np.mean():**

When you need a simple average and no weighting is required. When performance is a priority, and you don’t need any extra features like weight handling. For typical applications where all values contribute equally to the mean, like computing the mean of temperature readings or scores.

**Use np.average():**

When you need a weighted average, where some elements should have a greater or lesser effect on the result. In applications like finance or physics, where different elements carry different levels of importance. For example, calculating the weighted average return of a portfolio where each asset has a different investment weight. If you want to retrieve the sum of weights along with the average, which np.mean() doesn’t provide.

**Q3. DESCRIBE A METHODS FOR REVERSING A NUMPY ARRAY ALONG DIFFERENT AXES. PROVIDE EXAMPLE FOR 1D AND 2D ARRAY.**

**ANS:** Reversing a NumPy array along different axes can be done using various methods. The most common techniques include using slicing, the np.flip() function, and np.flipud() / np.fliplr() for 2D arrays. Below are descriptions of these methods along with examples for both 1D and 2D arrays.

Reversing a 1D Array
Method: Slicing

You can reverse a 1D array by using slicing with a step of -1.

Example:

In [ ]:
import numpy as np
array_1d=np.array([1,2,3,4,5])
reversed_array_1d =array_1d[::-1]

print("Original 1D array:", array_1d)
print("Reversed 1D array:",reversed_array_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


Method: Using np.flip()

You can also use the np.flip() function, which allows for reversing along specified axes(for 1D, it will only reverse the entire array).

Example:

In [ ]:
reversed_array_1d_flip=np.flip(array_1d)

print("Reversed 1D array using np.flip():",reversed_array_1d_flip)

Reversed 1D array using np.flip(): [5 4 3 2 1]


2. Reversing a 2D array

Method: Slicing

You canreverse a 2D array along different axes using slicing. The axis can be specified by using: for the desired dimentions

Example:


In [ ]:
array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9,]])
reversed_array_2d = array_2d[::-1, ::-1]

print("original 2D array:")
print(array_2d)
print("reversed 2D array:")
print(reversed_array_2d)

original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
reversed 2D array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


Method: Using np.flip()

You can use np.flip() to reverse the array along a specific axis:

Reversing along axis 0 (rows): Flips the array vertically. Reversing along axis 1 (columns): Flips the array horizontally.

Example:

In [ ]:
reversed_array_2d_axis0= np.flip(array_2d, axis=0)

reversed_array_2d_axis1 = np.flip(array_2d, axis=1)

print("reversed 2D array along axis 0 (rows):")
print(reversed_array_2d_axis0)
print("Reversed 2D array along axis 1 (columns):")
print(reversed_array_2d_axis1)

reversed 2D array along axis 0 (rows):
[[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array along axis 1 (columns):
[[3 2 1]
 [6 5 4]
 [9 8 7]]


**Q4. HOW CAN YOU DETERMINE THE DATA TYPE OF ELEMENTS IN A NUMPY ARRAY? DISCUSS THE IMPORTANCE OF DATA TYPES IN MEMORY MANAGEMENT AND PERFORMANCE.**

ANS: To determine the data type of elements in a NumPy array, .dtype attribute is used.

In [ ]:
import numpy as np

array =np.array([1,2,3,4,5,])
array.dtype

dtype('int64')

**Importance of Data Types in Memory Management and Performance**

1-Memory Efficiency
Different data types have different memory requirements. For example, int8 (8-bit integer) requires 1 byte per element, while int64 (64-bit integer) requires 8 bytes per element. Choosing an appropriate data type can save memory, which is especially important when dealing with large datasets. For instance, an array of 1,000,000 elements with int8 data type will consume only 1 MB of memory, whereas an array with int64 will consume 8 MB for the same data.

2-Performance Optimization
Operations on smaller data types (e.g., int8 or float32) are typically faster than on larger types (e.g., int64 or float64). Choosing a smaller data type can lead to significant performance gains when performing calculations, as less memory needs to be accessed and processed. For example, in applications that require real-time computations (such as signal processing or image processing), using float32 instead of float64 can speed up calculations without significantly affecting accuracy.

3-Compatibility and Precision
Using the correct data type helps maintain accuracy, especially for floating-point calculations. For instance, float64 provides higher precision than float32, which can be essential for scientific calculations where precision is crucial. Mismatched data types can lead to unexpected results or overflow errors. For instance, if an array of int8 (range -128 to 127) encounters a value beyond this range, it may cause overflow and wrap around, yielding incorrect results.

4-Operations and Broadcasting
NumPy arrays with different data types can sometimes lead to issues in operations, as arrays of the same data type are required for element-wise operations and broadcasting. Knowing and standardizing the data types across arrays can prevent errors and make computations more straightforward.




**Q5. DEFINE ndarrays IN NUMPY AND EXPLAIN THEIR KEY FEATURES. HOW DO THEY DIFFERE FROM STANDARD PYTHON LISTS?**

ANS: An ndarray is an n-dimensional, homogeneous array, meaning that all elements within the array are of the same data type. It can represent data in one dimension (1D), like a list of numbers, or in higher dimensions, such as matrices (2D) or tensors (3D and above).

**Key Features of ndarrays**

**1. Homogeneous Data Type:**

All elements in an ndarray must be of the same data type (e.g., all integers, all floats, or all strings). This consistency allows for efficient storage and quick calculations, as memory layout and element size are predictable.

**2. Multidimensional Support:**

ndarrays can have multiple dimensions, from 1D (a simple array) to n-dimensional, where n can be any non-negative integer. For example, a 2D ndarray represents a matrix, while a 3D ndarray can represent a tensor.

**3. Fixed Size:**

Once created, the size (number of elements) of an ndarray is fixed. You can reshape the array but cannot directly change its size. This differs from Python lists, which are dynamically resizable.

**4. Efficient Memory Layout:**

ndarrays use contiguous memory blocks, which optimizes performance for operations like slicing, accessing, and performing mathematical operations. They store data in a compact form, making them memory-efficient, especially compared to lists of lists in Python.

**Differences Between ndarrays and Python Lists**

**ndarray Python List**

1-DATA TYPE: Homogeneous (same data type)
2-MEMORY LAYOUT: Contiguous and optimized
3-DIMENSIONS: Supports n-dimensions
4-PERFORMANCE: Highly optimized for numerical operations

**Python List**

1-DATA TYPE: Heterogeneous (mixed data types)
2-MEMORY LAYOUT: Not contiguous; linked references
3-DIMENSIONS: 1D; requires nested lists for 2D+
4-PERFORMANCE: Slower for numerical computations


**Q6. ANALYZE THE PERFORMANCE BENEFITS OF NUMPY ARRAYS OVER PYTHON LISTS FOR LARGE-SCALE NUMERICAL OPERATIONS.**

ANS: Key Performance Benefits of NumPy Arrays over Python Lists

1-Efficient Memory Layout:
Fixed Data Type: NumPy arrays are homogeneous, meaning all elements are of the same data type, unlike Python lists, which are heterogeneous and can store elements of different types. This homogeneity allows NumPy arrays to store elements in contiguous blocks of memory, making memory access and retrieval faster.

Compact Storage: Because NumPy knows the type of data it is storing, it can allocate just the right amount of memory for each element. For example, an int32 array uses exactly 4 bytes per integer, whereas Python lists use additional memory to store type information and references for each element.

2-Vectorized Operations:
NumPy supports vectorized operations, meaning that mathematical and logical operations can be applied to entire arrays at once without explicit loops. Python lists, on the other hand, require looping through elements to perform similar operations.

Vectorized operations are internally implemented in low-level languages like C, allowing NumPy to perform computations at a much faster speed than Python's interpreted loop-based approach.

For example, multiplying each element of a NumPy array by 2 is significantly faster than iterating through a Python list and performing the same operation.

3-Broadcasting:
Broadcasting is a feature that allows NumPy to perform operations between arrays of different shapes without needing to manually reshape or expand them. This capability reduces the amount of code required and improves performance by minimizing unnecessary data replication.

4-Optimized Mathematical and Statistical Functions: NumPy provides a vast library of highly optimized functions for common numerical tasks (e.g., sum, mean, standard deviation), all implemented in lower-level languages like C, which are much faster than their Python equivalents.
For instance, calculating the mean of a NumPy array using np.mean() is far quicker than calculating it with a loop over a Python list.

**Q7. COMPARE VSTACK() AND HSTACK() FUNCTIONS IN NUMPY. PROVIDE EXAMPLES DEMONSTRATING THEIR USAGE AND OUTPUT.**

ANS: The vstack() and hstack() functions in NumPy are used to stack arrays along different axes, enabling you to combine arrays either vertically or horizontally. Here’s a comparison of the two functions, along with examples that demonstrate their usage.

**numpy.vstack()**

The vstack() function (short for "vertical stack") stacks arrays vertically, i.e., along rows. It requires that the arrays have the same number of columns but allows a different number of rows. vstack() can be used with both 1D and 2D arrays, but it will add a new row for each input if they’re 1D arrays.

Axis for stacking: Along the first axis (axis=0), which corresponds to rows.

Shape compatibility: Arrays must have the same number of columns (second dimension).



In [ ]:
#example with 1D arrays:
import numpy as np

array1= np.array([1,2,3,4])
array2= np.array([5,6,7,8])

result_vstack_1d= np.vstack((array1, array2))
print("Results of vstack with 1D arrays:")
print(result_vstack_1d)

Results of vstack with 1D arrays:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#example with 2D arrays:

array3= np.array([[1,2,3],[4,5,6]])
array4=np.array([[7,8,9],[10,11,12]])

result_vstack_2d= np.vstack((array3,array4))
print("Result of vstack with 2D arrays:")
print(result_vstack_2d)


Result of vstack with 2D arrays:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**numpy.hstack()**

The hstack() function (short for "horizontal stack") stacks arrays horizontally, i.e., along columns. It requires that the arrays have the same number of rows but allows a different number of columns. hstack() can be used with both 1D and 2D arrays, and if the arrays are 1D, they will be combined into a single row.

Axis for stacking: Along the second axis (axis=1), which corresponds to columns.

Shape compatibility: Arrays must have the same number of rows (first dimension).

In [9]:
#example with 1D array:
import numpy as np
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

result_hstack_1d=np.hstack((array1,array2))
print("result of hstack with 1D arrays:")
print(result_hstack_1d)

result of hstack with 1D arrays:
[1 2 3 4 5 6 7 8]


In [10]:
#example with 2D arrays:

array5=np.array([[1,2],[3,4]])
array6=np.array([[5,6],[7,8]])

result_hstack_2d=np.hstack((array5,array6))
print("result of hstack with 2D arrays:")
print(result_hstack_2d)

result of hstack with 2D arrays:
[[1 2 5 6]
 [3 4 7 8]]


**Q8. EXPLAIN THE DIFFERENCES BETWEEN fliplr() and flipud() METHODS IN NUMPY,INCLUDING THEIR EFFECTS ON VARIOUS ARRAY DIMENSIONS.**

ANS: In NumPy, the fliplr() and flipud() functions are used to reverse the elements of arrays along specific axes. These functions provide simple ways to mirror an array along different dimensions, making them useful in data manipulation and transformation tasks.

**numpy.fliplr()**

The fliplr() function (short for "flip left to right") reverses the elements of an array along the second axis (columns), effectively flipping the array horizontally. It is typically used with 2D arrays or higher-dimensional arrays where there is a second axis to operate on.

**Effect:** Flips the array horizontally by reversing the order of columns. Axis: Works along axis 1 (columns).

**Requirement:** The array must have at least 2 dimensions; otherwise, fliplr() will raise an error.



In [11]:
#EXAMPLE WITH 2D ARRAY


import numpy as np


array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


result_fliplr = np.fliplr(array_2d)
print("Original array:\n", array_2d)
print("\nArray after fliplr:\n", result_fliplr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after fliplr:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [12]:
#EXAMPLE WITH 3D ARRAY

array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])


result_fliplr_3d = np.fliplr(array_3d)
print("Original 3D array:\n", array_3d)
print("\n3D array after fliplr:\n", result_fliplr_3d)


Original 3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3D array after fliplr:
 [[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]


**numpy.flipud()**

The flipud() function (short for "flip up to down") reverses the elements of an array along the first axis (rows), effectively flipping the array vertically. This function is used primarily with 2D arrays or higher-dimensional arrays with at least one row.

Effect: Flips the array vertically by reversing the order of rows. Axis: Works along axis 0 (rows).

Requirement: Can be applied to any array with at least one dimension.

In [13]:
#EXAMPLE WITH 2D ARRAY

array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


result_flipud = np.flipud(array_2d)
print("Original array:\n", array_2d)
print("\nArray after flipud:\n", result_flipud)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after flipud:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [14]:
#EXAMPLE WITH 3D ARRAY

# Define a 3D array
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])

# Apply flipud
result_flipud_3d = np.flipud(array_3d)
print("Original 3D array:\n", array_3d)
print("\n3D array after flipud:\n", result_flipud_3d)


Original 3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

3D array after flipud:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


**Q9. DISCUSS THE FUNTIONALITY OF THE ARRAY _SPLIT() METHOD IN NUMPY.HOW DOES IT HANDLE UNEVEN SPLITS?**

ANS: The array_split() function divides an array into a specified number of sections or at specified indices along a given axis. If the array cannot be split evenly into the specified sections, array_split() adjusts the splits to ensure each section has as close to the same number of elements as possible.

**Handling Uneven Splits**

If indices_or_sections is an integer, and the array does not divide evenly into the specified number of splits, array_split() will create some sub-arrays that contain an extra element, if necessary. This ensures that the array is split as evenly as possible, and each resulting sub-array is contiguous.

For example, if you have an array of 10 elements and you split it into 3 sections, the first two sections will contain 4 elements, and the last section will contain 2 elements.

**Q10. EXPLAIN THE CONCEPTS OF VECTORIZATION AND BROADCASTING IN NUMPY. HOW DO THEY CONTRIBUTE TO EFFICIENT ARRAY OPERATIONS?**

ANS: Vectorization

Vectorization refers to the process of applying operations directly on entire arrays (or "vectors") without needing to loop through individual elements. NumPy’s internal functions are optimized for such vectorized operations, often implemented in lower-level languages (like C or Fortran) for maximum performance.

**In vectorization:**

1-Operations are applied element-wise on arrays.

2-Calculations are parallelized internally, taking advantage of hardware optimizations such as SIMD (Single Instruction, Multiple Data).

3-It allows you to perform complex mathematical computations in a single line, making code more concise and readable.

**Broadcasting**

Broadcasting is a technique that enables NumPy to perform operations on arrays of different shapes and sizes by automatically "stretching" one or both arrays to make their shapes compatible. When two arrays are not the same shape, broadcasting makes them compatible by virtually expanding the smaller array (without copying data), so that element-wise operations can be performed.

**Broadcasting Rules**

1-If arrays have different numbers of dimensions: The smaller array is padded with ones on its left side until both arrays have the same number of dimensions.

2-If arrays have the same number of dimensions but different shapes: For each dimension, if the sizes are unequal, the smaller dimension is either:

*Expanded (or "stretched") to match the larger dimension, if it is 1.
*Otherwise, the operation fails with a ValueError.
Broadcasting allows efficient computation without duplicating data, as NumPy performs operations by virtually expanding the smaller array as needed.

**Benefits of Vectorization and Broadcasting**

1-Performance Optimization:
Vectorized and broadcasted operations avoid explicit loops, making computations much faster. Both techniques leverage low-level, optimized C code, resulting in faster execution compared to pure Python loops.

2-Memory Efficiency:
Broadcasting avoids unnecessary duplication of data, as NumPy doesn’t create multiple copies of the smaller array. These techniques allow for efficient use of memory, which is especially beneficial when working with large datasets.

3-Readable and Concise Code:
Vectorization and broadcasting allow complex array operations to be expressed in a single line of code, improving readability and reducing the chance of errors.

4-Parallel Processing:
These operations can take advantage of hardware-level parallelism, such as multi-core CPUs or GPUs, for faster computation.

**PRACTICALS QUESTIONS**


**Q1. CREATE A 3*3 NUMPY ARRAY WITH RANDOM INTEGERS BETWEEN 1 AND 100. THEN INTERCHANGE ITS ROWS AND COLUMNS**

In [16]:
import numpy as np
array=np.random.randint(1,100, size=(3,3))
array

array([[37, 19, 51],
       [62, 85,  8],
       [99, 59, 27]])

In [18]:
array.T

array([[37, 62, 99],
       [19, 85, 59],
       [51,  8, 27]])

**Q2. GENERATE A 1D NUMPY ARRAY WITH 10 ELEMENTS. RESHAPE IT INTO A 25 ARRAY, THEN INTO A 52 ARRAY.**

In [21]:
arr=np.array([2,3,11,33,4,5,56,6,76,23])

arr.reshape(2,5)

array([[ 2,  3, 11, 33,  4],
       [ 5, 56,  6, 76, 23]])

In [23]:
arr.reshape(5,2)

array([[ 2,  3],
       [11, 33],
       [ 4,  5],
       [56,  6],
       [76, 23]])

**Q3. CREATE A 44 NUMPY ARRAY WITH RANDOM FLOAT VALUES.ADD A BORDER OF ZEROES AROUND IT, RESULTING IN A 66 ARRAY.**



In [28]:
original_array=np.random.rand(4,4)

bordered_array=np.pad(original_array,pad_width=1,mode='constant',constant_values=0)

print("original 4x4 array:\n", original_array)
print("\nbordered 6x6 array:\n", bordered_array)

original 4x4 array:
 [[0.3363966  0.53483069 0.42210584 0.67993327]
 [0.6566635  0.59349902 0.45629163 0.15938315]
 [0.64435511 0.96349423 0.81242365 0.15891263]
 [0.9896082  0.75595128 0.77367092 0.13359196]]

bordered 6x6 array:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.3363966  0.53483069 0.42210584 0.67993327 0.        ]
 [0.         0.6566635  0.59349902 0.45629163 0.15938315 0.        ]
 [0.         0.64435511 0.96349423 0.81242365 0.15891263 0.        ]
 [0.         0.9896082  0.75595128 0.77367092 0.13359196 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Q4. USING NUMPY , CREATE AN ARRAY OF INTEGERS FROM 10 TO 60 WITH A STEP OF 5.**



In [29]:
array= np.arange(10,60,5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

**Q5. CREATE A NUMPY ARRAY OF STRINGS ['python','numpy','pandas'].APPLY DIFFERENT CASE TRANSFORMATIONS (UPPERCASE,LOWERCASE,TITLE CASE ETC) TO EACH ELEMENT.**

In [30]:
strings= np.array(['python','numpy','pandas'])

uppercase=np.char.upper(strings)
lowercase= np.char.lower(strings)
titlecase=np.char.title(strings)
capitalize=np.char.capitalize(strings)

print("original array:",strings)
print("uppercase:",uppercase)
print("lowercase:",lowercase)
print("titlecase:",titlecase)
print("capitalized:",capitalize)

original array: ['python' 'numpy' 'pandas']
uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
lowercase: ['python' 'numpy' 'pandas']
titlecase: ['Python' 'Numpy' 'Pandas']
capitalized: ['Python' 'Numpy' 'Pandas']


**Q6. GENERATE A NUMPY ARRAY OF WORDS . INSERT A SPACE BETWEEN EACH CHARACTER OF EVERY WORD IN THE ARRAY.**



In [31]:
words = np.array(['hello', 'numpy', 'python', 'array'])


spaced_words = np.char.join(' ', words)


print("Original Array:", words)
print("Spaced Words:", spaced_words)


Original Array: ['hello' 'numpy' 'python' 'array']
Spaced Words: ['h e l l o' 'n u m p y' 'p y t h o n' 'a r r a y']


**Q7. CREATE TWO 2D NUMPY ARRAYS AND PERFORM ELEMENT-WISE ADDITION, SUBSTRACTION, MULTIPLICATION AND DIVISION.**

In [3]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[7,8,9],[10,11,12]])

array1 + array2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
array1-array2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [5]:
array1*array2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [6]:
array1/array2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

**Q8. USE NUMPY TO CREATE A 5*5 IDENTITY MATRIX ,THEN EXTRACT ITS DIAGONAL ELEMENTS.**

In [7]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.diagonal(a)

array([1., 1., 1., 1., 1.])

**Q9. GENERATE A NUMPY ARRAY OF 100 RANDOM INTEGERS BETWEEN 0 AND 1000. FIND AND DISPLAY ALL PRIME NUMBERS IN THIS ARRAY.**

In [12]:
def is_prime(n):
  if n<=1:
    return False
  for i in range(2, int(n**0.5)+1):
    if n% i==0:
      return False
  return True

random_integers = np.random.randint(0, 1000, size=100)
prime_numbers= [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("\nPrime Numbers:", prime_numbers)

Random Integers:
 [642  50 885 306 610 182 714 666  36 807 371 830 708 515 684 450 642 838
 758 723 307 649 674 655  45 207 240 649  32 701 456 508 183 823 796 823
 728  33 657 359 881 710 684  56 180 286 836 456 156 342 423 823 682 360
 799 506 587 953 657 718 208 954 256 413  41 913 471 954 382 859 286 341
 601 265 915 522 707 980 645 154 988 713 100 870 198 221 369 391 623 344
 437 368 918 688 305 870 138 948 164 265]

Prime Numbers: [307, 701, 823, 823, 359, 881, 823, 587, 953, 41, 859, 601]


**Q10. CREATE A NUMPY ARRAY REPRESENTING DAILY TEMPERATURES FOR A MONTH. CALCULATE AND DISPLAY THE WEEKLY AVERAGES.**

In [15]:
np.random.seed(0)
daily_temperatures= np.random.randint(15,31, size=28)

weekly_temperatures= daily_temperatures.reshape(4,7)

weekly_averages= np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:", weekly_averages)

Daily Temperatures for the Month:
 [27 30 20 15 18 26 18 22 24 18 20 17 19 22 21 23 23 27 25 16 21 22 22 29
 23 16 20 24]

Weekly Temperatures:
 [[27 30 20 15 18 26 18]
 [22 24 18 20 17 19 22]
 [21 23 23 27 25 16 21]
 [22 22 29 23 16 20 24]]

Weekly Averages: [22.         20.28571429 22.28571429 22.28571429]
